//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web365Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPicture
    {
        public tblPicture()
        {
            this.tblAdverties_Picture_Map = new HashSet<tblAdverties_Picture_Map>();
            this.tblArticle = new HashSet<tblArticle>();
            this.tblCustomer = new HashSet<tblCustomer>();
            this.tblDistributor = new HashSet<tblDistributor>();
            this.tblFile = new HashSet<tblFile>();
            this.tblGroupArticle = new HashSet<tblGroupArticle>();
            this.tblGroupTypeArticle = new HashSet<tblGroupTypeArticle>();
            this.tblLayoutContent = new HashSet<tblLayoutContent>();
            this.tblManufacturer = new HashSet<tblManufacturer>();
            this.tblProduct = new HashSet<tblProduct>();
            this.tblProductLabel = new HashSet<tblProductLabel>();
            this.tblTypeArticle = new HashSet<tblTypeArticle>();
            this.tblTypeFile = new HashSet<tblTypeFile>();
            this.tblTypePicture1 = new HashSet<tblTypePicture>();
            this.tblTypeProduct = new HashSet<tblTypeProduct>();
            this.tblTypeVideo = new HashSet<tblTypeVideo>();
            this.tblVideo = new HashSet<tblVideo>();
            this.tblArticle1 = new HashSet<tblArticle>();
            this.tblProduct1 = new HashSet<tblProduct>();
            this.tblTypeProduct1 = new HashSet<tblTypeProduct>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Summary { get; set; }
        public string Alt { get; set; }
        public string Link { get; set; }
        public Nullable<long> Size { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<tblAdverties_Picture_Map> tblAdverties_Picture_Map { get; set; }
        public virtual ICollection<tblArticle> tblArticle { get; set; }
        public virtual ICollection<tblCustomer> tblCustomer { get; set; }
        public virtual ICollection<tblDistributor> tblDistributor { get; set; }
        public virtual ICollection<tblFile> tblFile { get; set; }
        public virtual ICollection<tblGroupArticle> tblGroupArticle { get; set; }
        public virtual ICollection<tblGroupTypeArticle> tblGroupTypeArticle { get; set; }
        public virtual ICollection<tblLayoutContent> tblLayoutContent { get; set; }
        public virtual ICollection<tblManufacturer> tblManufacturer { get; set; }
        public virtual tblTypePicture tblTypePicture { get; set; }
        public virtual ICollection<tblProduct> tblProduct { get; set; }
        public virtual ICollection<tblProductLabel> tblProductLabel { get; set; }
        public virtual ICollection<tblTypeArticle> tblTypeArticle { get; set; }
        public virtual ICollection<tblTypeFile> tblTypeFile { get; set; }
        public virtual ICollection<tblTypePicture> tblTypePicture1 { get; set; }
        public virtual ICollection<tblTypeProduct> tblTypeProduct { get; set; }
        public virtual ICollection<tblTypeVideo> tblTypeVideo { get; set; }
        public virtual ICollection<tblVideo> tblVideo { get; set; }
        public virtual ICollection<tblArticle> tblArticle1 { get; set; }
        public virtual ICollection<tblProduct> tblProduct1 { get; set; }
        public virtual ICollection<tblTypeProduct> tblTypeProduct1 { get; set; }
    }
}
