//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đang được cập nhật.
        /// </summary>
        internal static string ArticleLabelEmpty {
            get {
                return ResourceManager.GetString("ArticleLabelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sales@vincomshophouse.vn.
        /// </summary>
        internal static string EmailContact {
            get {
                return ResourceManager.GetString("EmailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LangugeCode {
            get {
                return ResourceManager.GetString("LangugeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIỚI THIỆU.
        /// </summary>
        internal static string lblAbout {
            get {
                return ResourceManager.GetString("lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string lblAboutDetail {
            get {
                return ResourceManager.GetString("lblAboutDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string lblContactDetail {
            get {
                return ResourceManager.GetString("lblContactDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu.
        /// </summary>
        internal static string lblDocument {
            get {
                return ResourceManager.GetString("lblDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu.
        /// </summary>
        internal static string lblDocumentDetail {
            get {
                return ResourceManager.GetString("lblDocumentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện ảnh.
        /// </summary>
        internal static string lblLibraryImages {
            get {
                return ResourceManager.GetString("lblLibraryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện Video.
        /// </summary>
        internal static string lblLibraryVideo {
            get {
                return ResourceManager.GetString("lblLibraryVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUNG TÂM THƯƠNG MẠI.
        /// </summary>
        internal static string lblMall {
            get {
                return ResourceManager.GetString("lblMall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung tâm thương mại.
        /// </summary>
        internal static string lblMallDetail {
            get {
                return ResourceManager.GetString("lblMallDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800 1066.
        /// </summary>
        internal static string lblPhoneHotline {
            get {
                return ResourceManager.GetString("lblPhoneHotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VỊ TRÍ.
        /// </summary>
        internal static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        internal static string lblPositionDetail {
            get {
                return ResourceManager.GetString("lblPositionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        internal static string lblProject {
            get {
                return ResourceManager.GetString("lblProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOPHOUSE.
        /// </summary>
        internal static string lblShopHouse {
            get {
                return ResourceManager.GetString("lblShopHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shophouse.
        /// </summary>
        internal static string lblShopHouseDetail {
            get {
                return ResourceManager.GetString("lblShopHouseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chia sẻ Shophouse.
        /// </summary>
        internal static string lblTextShare {
            get {
                return ResourceManager.GetString("lblTextShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        internal static string lblVietNam {
            get {
                return ResourceManager.GetString("lblVietNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://facebook.com.
        /// </summary>
        internal static string LinkFacebook {
            get {
                return ResourceManager.GetString("LinkFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://instagram.com/.
        /// </summary>
        internal static string LinkInstagram {
            get {
                return ResourceManager.GetString("LinkInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.pinterest.com/.
        /// </summary>
        internal static string LinkPinterest {
            get {
                return ResourceManager.GetString("LinkPinterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/.
        /// </summary>
        internal static string LinkTwitter {
            get {
                return ResourceManager.GetString("LinkTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18001066.
        /// </summary>
        internal static string PhoneHotline {
            get {
                return ResourceManager.GetString("PhoneHotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng ký.
        /// </summary>
        internal static string RegisterLabel {
            get {
                return ResourceManager.GetString("RegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string RegisterLabelBirthDay {
            get {
                return ResourceManager.GetString("RegisterLabelBirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegisterLabelEmail {
            get {
                return ResourceManager.GetString("RegisterLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ông.
        /// </summary>
        internal static string RegisterLabelMan {
            get {
                return ResourceManager.GetString("RegisterLabelMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string RegisterLabelName {
            get {
                return ResourceManager.GetString("RegisterLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string RegisterLabelPhone {
            get {
                return ResourceManager.GetString("RegisterLabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án quan tâm.
        /// </summary>
        internal static string RegisterLabelProject {
            get {
                return ResourceManager.GetString("RegisterLabelProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string RegisterLabelSubmit {
            get {
                return ResourceManager.GetString("RegisterLabelSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bà.
        /// </summary>
        internal static string RegisterLabelWoman {
            get {
                return ResourceManager.GetString("RegisterLabelWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả tìm kiếm với từ khóa &quot;{0}&quot;.
        /// </summary>
        internal static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tin thấy kết dữ liệu. Bạn vui lòng thử lại với từ khóa khác..
        /// </summary>
        internal static string SearchLabelEmpty {
            get {
                return ResourceManager.GetString("SearchLabelEmpty", resourceCulture);
            }
        }
    }
}
